# Generated by Django 2.1.4 on 2019-04-18 10:08

from django.db import migrations, models
import djssoclient.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSOUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('extras', models.TextField(default=djssoclient.models.default_dumpped_dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
