# Generated by Django 2.1.4 on 2019-04-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTableIndex',
            fields=[
                ('sourcename', models.CharField(db_column='sourceName', max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('targetname', models.CharField(db_column='targetName', max_length=255, primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('filesize', models.BigIntegerField(blank=True, db_column='fileSize', null=True)),
            ],
            options={
                'db_table': 'data_table_index',
                'managed': False,
            },
        ),
    ]
